### ISSUE TITLE
Build Error referencing MessageQueuing

### ISSUE THREAD

**Issue by bljack333** [dejanstojanovic/MessageQueue-Manager#1]
Hi,

The project referencing MessageQueuing is targeting 4.5.  It appears that MessageQueuing was built against 4.5.2.  Hoping you can provide a 4.5 version.

Here's the messages I getting:
Error   2   The type or namespace name 'MessageQueuing' could not be found (are you missing a using directive or an assembly reference?)    --  7   7   --

Warning 3   The primary reference "MessageQueuing" could not be resolved because it was built against the ".NETFramework,Version=v4.5.2" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".    C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets 1697    5   --

Thanks,
Mike

**Comment by dejanstojanovic** [comment]
No problem, I'll have a look at this issue and get back to you as soon as possible

**Comment by dejanstojanovic** [comment]
Hi @bljack333,
Try to change the target framework for class library project MessageQueuing to 4.5 and rebuild that project.
This should solve the references issue in your solution. I tried on my machine and it worked just fine.
Let me know if you need any help with this.

**Comment by dejanstojanovic** [comment]
Hi @bljack333,
Were you able to build the solution?
