### ISSUE TITLE
How to get notifications

### ISSUE THREAD

**Issue by smartmeter** [dejanstojanovic/MessageQueue-Manager#2]
Hi, I have become a fan of your work :+1: 

I am trying to use this to get notification for a form approval, like a purchase request -> to Mgr -> approval -> employee

How can I achieve this with this.

thanks

**Comment by dejanstojanovic** [comment]
You can make one application write to queue and the other one can read from the same one using an event handler. Make sure you use the same model class in both applications so the massage from the queue can be serialized on writing and deserialized on reading

**Comment by smartmeter** [comment]
how does it end up in the queue, what is the process to end up the queue.

Lets say, purchase request submitted, then approved - in the DB table PirchaseOrdr, I am updating the status, 
1. how do I ensure it goes to the queue to the correct target/destination/**user**/group - to whom it was approved
2. how do I ensure the app peeks only his items, and only when he logs in (do i need a queue per user? or do I query the queue with your mgr?)

**Comment by dejanstojanovic** [comment]
See, you add all to queue and read all from queue. You use it only to communicate between two applications. Internally in your read application you can specify what to do with the message. I do not really understand your flow, but basically queues are simple, just to pass something to it and reader can pick it up when reading

**Comment by smartmeter** [comment]
ok thanks for exp.

I think my case is different, kind of like pub/sub.

My goal: I was hoping to to use the queue to notify a user when he logs in, on any pending items. Since the queue is not event driven, I was going to peek through the queue with your manager to notify the user of pending tasks.

Now I see its a consuming manager, I am sorry I thought it had notifications capability.
